'use client'

import { useState } from 'react'

export type PropertyIntent = 'sell' | 'rent'

interface Props {
  onSelect: (intent: PropertyIntent) => void
}

export default function Step0Intent({ onSelect }: Props) {
  const [hovered, setHovered] = useState<PropertyIntent | null>(null)

  const options: {
    id: PropertyIntent
    icon: string
    title_en: string
    title_ru: string
    title_de: string
    desc_en: string
    desc_ru: string
    desc_de: string
    features_en: string[]
    features_ru: string[]
  }[] = [
    {
      id: 'sell',
      icon: '🏷️',
      title_en: 'Sell',
      title_ru: 'Продать',
      title_de: 'Verkaufen',
      desc_en: 'AI-powered distribution to 847+ buyer agencies across 31 EU markets',
      desc_ru: 'AI-рассылка в 847+ агентств по покупке в 31 рынке ЕС',
      desc_de: 'KI-Verteilung an 847+ Käufer-Agenturen in 31 EU-Märkten',
      features_en: [
        'Sales letter + photo pack generated by AI',
        'Agencies matched by buyer profile & cross-border history',
        'Wave 1: 10 agencies → Wave 2: 10 more after 48h',
        'All inquiries forwarded to you via email + Telegram',
        'Billing stops automatically when sold',
      ],
      features_ru: [
        'Продающее письмо + пакет фото генерируется ИИ',
        'Агентства подбираются по профилю покупателя',
        'Волна 1: 10 агентств → Волна 2: ещё 10 через 48ч',
        'Все запросы пересылаются вам по email + Telegram',
        'Оплата останавливается при продаже',
      ],
    },
    {
      id: 'rent',
      icon: '🏠',
      title_en: 'Rent Out',
      title_ru: 'Сдать в аренду',
      title_de: 'Vermieten',
      desc_en: 'Connect with specialised rental & property management agencies',
      desc_ru: 'Подключитесь к специализированным агентствам аренды',
      desc_de: 'Verbinden Sie sich mit spezialisierten Vermietungsagenturen',
      features_en: [
        'Long-term rental (6+ months)',
        'Property management companies included',
        'Rental valuation included in AI package',
        'Tenant screening via partner agencies',
        'Available in 31 EU markets',
      ],
      features_ru: [
        'Долгосрочная аренда (6+ месяцев)',
        'Управляющие компании включены',
        'Оценка аренды в AI-пакете',
        'Проверка арендаторов через агентства',
        'Доступно в 31 рынке ЕС',
      ],
    },
  ]

  return (
    <div className="max-w-3xl mx-auto">
      <div className="text-center mb-10">
        <h2 className="text-3xl font-black text-white mb-3">What do you want to do?</h2>
        <p className="text-white/40">
          Choose your path — we'll customise the wizard and agency matching accordingly.
        </p>
      </div>

      <div className="grid sm:grid-cols-2 gap-5">
        {options.map((opt) => (
          <button
            key={opt.id}
            onClick={() => onSelect(opt.id)}
            onMouseEnter={() => setHovered(opt.id)}
            onMouseLeave={() => setHovered(null)}
            className="text-left p-7 rounded-3xl border transition-all duration-300 group"
            style={{
              background:
                hovered === opt.id
                  ? 'linear-gradient(135deg, rgba(220,38,38,0.12), rgba(234,88,12,0.06))'
                  : 'rgba(255,255,255,0.03)',
              borderColor:
                hovered === opt.id
                  ? 'rgba(220,38,38,0.4)'
                  : 'rgba(255,255,255,0.08)',
              boxShadow:
                hovered === opt.id
                  ? '0 16px 40px rgba(220,38,38,0.12)'
                  : 'none',
              transform: hovered === opt.id ? 'translateY(-2px)' : 'translateY(0)',
            }}
          >
            <div className="flex items-center gap-4 mb-4">
              <div
                className="w-14 h-14 rounded-2xl flex items-center justify-center text-2xl transition-all"
                style={{
                  background:
                    hovered === opt.id
                      ? 'linear-gradient(135deg, #dc2626, #ea580c)'
                      : 'rgba(255,255,255,0.05)',
                  border:
                    hovered === opt.id
                      ? 'none'
                      : '1px solid rgba(255,255,255,0.1)',
                }}
              >
                {opt.icon}
              </div>
              <div>
                <div className="text-2xl font-black text-white">{opt.title_en}</div>
                <div className="text-sm text-white/40">{opt.title_ru} · {opt.title_de}</div>
              </div>
            </div>

            <p className="text-sm text-white/60 mb-5 leading-relaxed">{opt.desc_en}</p>

            <ul className="space-y-2">
              {opt.features_en.map((f) => (
                <li key={f} className="flex items-start gap-2.5 text-sm text-white/50">
                  <svg className="w-4 h-4 mt-0.5 shrink-0" viewBox="0 0 16 16" fill="none">
                    <path
                      d="M5 8l2 2 4-4"
                      stroke={hovered === opt.id ? '#ea580c' : 'rgba(255,255,255,0.3)'}
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  {f}
                </li>
              ))}
            </ul>

            <div
              className="mt-6 flex items-center gap-2 text-sm font-semibold transition-colors"
              style={{ color: hovered === opt.id ? '#f97316' : 'rgba(255,255,255,0.25)' }}
            >
              Select {opt.title_en}
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M2 7h10M8 3l4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
              </svg>
            </div>
          </button>
        ))}
      </div>

      <p className="text-center text-xs text-white/20 mt-8">
        You can change this at any time · Both paths use the same AI matching engine
      </p>
    </div>
  )
}
