export const DEMO_AGENCIES = [
  {
    id: 'agency-001',
    name: 'Engel & Völkers Adriatic',
    email: 'info@engelvoelkers-adriatic.me',
    website: 'engelvoelkers.com/adriatic',
    country: 'Montenegro',
    city: 'Budva',
    flag: '🇲🇪',
    specialization: 'Luxury Coastal Properties',
    languages: ['EN', 'DE', 'RU'],
    score: 97,
    deals_30d: 28,
    response_rate: 96,
    isRealEmail: false
  },
  {
    id: 'agency-002',
    name: 'Sotheby\'s Realty MNE',
    email: 'listings@sothebys-montenegro.me',
    website: 'sothebysrealty.com',
    country: 'Montenegro',
    city: 'Porto Montenegro',
    flag: '🇲🇪',
    specialization: 'Ultra-Luxury Investment',
    languages: ['EN', 'FR', 'IT'],
    score: 94,
    deals_30d: 18,
    response_rate: 92,
    isRealEmail: false
  },
  {
    id: 'agency-003',
    name: 'Savills International',
    email: 'property@savills.co.uk',
    website: 'savills.com',
    country: 'United Kingdom',
    city: 'London',
    flag: '🇬🇧',
    specialization: 'International Residential',
    languages: ['EN', 'DE', 'FR', 'IT'],
    score: 91,
    deals_30d: 42,
    response_rate: 94,
    isRealEmail: false
  },
  {
    id: 'agency-004',
    name: 'Knight Frank Serbia',
    email: 'belgrade@knightfrank.com',
    website: 'knightfrank.com',
    country: 'Serbia',
    city: 'Belgrade',
    flag: '🇷🇸',
    specialization: 'Commercial & Residential',
    languages: ['EN', 'SR', 'RU'],
    score: 88,
    deals_30d: 21,
    response_rate: 89,
    isRealEmail: false
  },
  {
    id: 'agency-005',
    name: 'Tranio Partners',
    email: 'info@tranio.de',
    website: 'tranio.com',
    country: 'Germany',
    city: 'Berlin',
    flag: '🇩🇪',
    specialization: 'International Investor Sales',
    languages: ['EN', 'DE', 'RU', 'FR'],
    score: 85,
    deals_30d: 35,
    response_rate: 91,
    isRealEmail: false
  },
  {
    id: 'agency-006',
    name: 'RE/MAX Adriatic Coast',
    email: 'hr@remaxadriaticcoast.hr',
    website: 'remax-adriatic.hr',
    country: 'Croatia',
    city: 'Split',
    flag: '🇭🇷',
    specialization: 'Coastal & Tourism Properties',
    languages: ['EN', 'HR', 'DE'],
    score: 82,
    deals_30d: 16,
    response_rate: 87,
    isRealEmail: false
  },
  {
    id: 'agency-007',
    name: 'Century 21 Montenegro',
    email: 'office@century21montenegro.me',
    website: 'century21.me',
    country: 'Montenegro',
    city: 'Podgorica',
    flag: '🇲🇪',
    specialization: 'Residential & Land',
    languages: ['EN', 'SR', 'RU'],
    score: 78,
    deals_30d: 12,
    response_rate: 84,
    isRealEmail: false
  },
  {
    id: 'agency-008',
    name: 'Gulf Property Investments',
    email: 'properties@gulfprop-invest.ae',
    website: 'gulfproperties.ae',
    country: 'United Arab Emirates',
    city: 'Dubai',
    flag: '🇦🇪',
    specialization: 'International HNW Sales',
    languages: ['EN', 'AR', 'FR'],
    score: 74,
    deals_30d: 31,
    response_rate: 88,
    isRealEmail: false
  },
  {
    id: 'agency-009',
    name: 'Win-Win Solution',
    email: 'contact@win-winsolution.com',
    website: 'win-winsolution.com',
    country: 'Serbia',
    city: 'Belgrade',
    flag: '🇷🇸',
    specialization: 'Residential & Commercial',
    languages: ['EN', 'RU', 'SR'],
    score: 96,
    deals_30d: 12,
    response_rate: 94,
    isRealEmail: true
  },
  {
    id: 'agency-010',
    name: 'Adriatic Estates',
    email: 'info@adriaticesates-demo.eu',
    website: 'adriaticestates.eu',
    country: 'Montenegro',
    city: 'Budva',
    flag: '🇲🇪',
    specialization: 'Sea View & Tourism',
    languages: ['EN', 'SR', 'RU'],
    score: 81,
    deals_30d: 8,
    response_rate: 85,
    isRealEmail: false
  }
];
