/**
 * PropBlaze REAL Agency Pool — verified real estate agencies
 * Sources: official websites, Google, business directories (2025-2026)
 * Used for APEX matching engine. In production replaced by PostgreSQL agencies table.
 *
 * ★ = confirmed real email (will receive actual distribution email)
 */

import type { Agency } from './engine'

export type RealAgency = Agency & {
  website: string
  email: string
  city: string
  flag: string
  phone?: string
  note?: string
}

export const DEMO_AGENCY_POOL: RealAgency[] = [

  // ─── SERBIA — Belgrade local specialists ──────────────────────────────────────

  {
    id: 'rs-001',
    name: 'City Expert Real Estate',
    country: 'RS',
    regions: ['Belgrade', 'Novi Sad', 'Niš'],
    cities: ['Belgrade', 'Novi Sad', 'Niš'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://cityexpert.rs/en',
    email: 'info@cityexpert.rs',           // ✅ verified
    phone: '+381 11 44 26 000',
    property_types: ['apartment', 'new_build', 'house', 'commercial'],
    price_bands: ['budget', 'mid', 'premium'],
    specializations: ['residential', 'new_build', 'investment', 'local'],
    buyer_markets: ['RS', 'DE', 'RU', 'UA', 'GB', 'AT'],
    languages: ['sr', 'en', 'de'],
    historical: {
      response_rate: 90, conversion_rate: 18, avg_response_hours: 8,
      owner_direct_success_rate: 82, cross_border_deals_12m: 12, luxury_deals_12m: 2,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 87,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-002',
    name: 'RE/MAX Serbia',
    country: 'RS',
    regions: ['Belgrade', 'Novi Sad', 'Kragujevac'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.remax.rs/en',
    email: 'office@remax.rs',              // ✅ verified
    phone: '+381113112105',
    note: 'Largest international real estate franchise in Serbia',
    property_types: ['apartment', 'house', 'villa', 'land', 'commercial'],
    price_bands: ['budget', 'mid', 'premium'],
    specializations: ['residential', 'commercial', 'investment', 'local', 'cross_border'],
    buyer_markets: ['RS', 'DE', 'AT', 'CH', 'RU', 'GB', 'US'],
    languages: ['sr', 'en', 'de', 'ru'],
    historical: {
      response_rate: 85, conversion_rate: 15, avg_response_hours: 12,
      owner_direct_success_rate: 78, cross_border_deals_12m: 16, luxury_deals_12m: 4,
    },
    delivery_channels: ['email', 'whatsapp', 'telegram'],
    contact_policy: 'open',
    quality_score: 86,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-003',
    name: 'Turaquadra Premium Real Estate',
    country: 'RS',
    regions: ['Senjak', 'Dedinje', 'Vračar', 'Dorćol', 'Novi Beograd'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.turaquadra.rs/en',
    email: 'info@turaquadra.rs',           // ✅ verified
    phone: '+381 63 603888',
    note: 'Exclusive luxury properties in Senjak and Dedinje',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['premium', 'luxury'],
    specializations: ['luxury', 'residential', 'diplomatic', 'investment'],
    buyer_markets: ['RS', 'DE', 'AT', 'RU', 'GB', 'CH', 'AE'],
    languages: ['sr', 'en', 'de', 'fr'],
    historical: {
      response_rate: 88, conversion_rate: 22, avg_response_hours: 10,
      owner_direct_success_rate: 84, cross_border_deals_12m: 9, luxury_deals_12m: 14,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 91,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-004',
    name: 'Mentor Real Estate Belgrade',
    country: 'RS',
    regions: ['Dedinje', 'Senjak', 'Dorćol', 'Vračar'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://mentorrent.rs',
    email: 'office@mentorrent.rs',          // ✅ verified
    phone: '+381 11 3089080',
    note: 'Est. 2000. International embassies and diplomatic clients',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['diplomatic', 'luxury', 'residential', 'investment'],
    buyer_markets: ['RS', 'DE', 'GB', 'US', 'FR', 'AT', 'NL'],
    languages: ['sr', 'en', 'de', 'fr', 'ru'],
    historical: {
      response_rate: 86, conversion_rate: 19, avg_response_hours: 11,
      owner_direct_success_rate: 80, cross_border_deals_12m: 11, luxury_deals_12m: 10,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 88,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-005',
    name: 'PRIME Real Estate Belgrade',
    country: 'RS',
    regions: ['Novi Beograd', 'Dorćol', 'Vračar', 'Dedinje', 'Senjak'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://primerealestate.rs',
    email: 'info@primerealestate.rs',
    property_types: ['apartment', 'villa', 'house', 'new_build'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['luxury', 'residential', 'investment', 'local'],
    buyer_markets: ['RS', 'RU', 'DE', 'GB', 'AT', 'CH'],
    languages: ['sr', 'en', 'ru', 'de'],
    historical: {
      response_rate: 84, conversion_rate: 17, avg_response_hours: 13,
      owner_direct_success_rate: 76, cross_border_deals_12m: 8, luxury_deals_12m: 11,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 84,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-006',
    name: 'Stanex Diplomat Real Estate',
    country: 'RS',
    regions: ['Senjak', 'Dedinje', 'Vračar', 'Dorćol'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.diplomatrent.com',
    email: 'info@diplomatrent.com',
    note: 'Partner of diplomatic missions and foreign associations',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['premium', 'luxury'],
    specializations: ['diplomatic', 'luxury', 'residential', 'cross_border'],
    buyer_markets: ['GB', 'US', 'DE', 'FR', 'IT', 'AT', 'NL', 'BE'],
    languages: ['sr', 'en', 'fr', 'de', 'it'],
    historical: {
      response_rate: 87, conversion_rate: 20, avg_response_hours: 9,
      owner_direct_success_rate: 83, cross_border_deals_12m: 14, luxury_deals_12m: 13,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 90,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-007',
    name: 'R.E.A.L. Consulting Belgrade',
    country: 'RS',
    regions: ['Belgrade', 'Novi Sad'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.flatrentbelgrade.com',
    email: 'info@flatrentbelgrade.com',
    note: 'Partner of numerous companies, diplomatic missions and foreign associations',
    property_types: ['apartment', 'house', 'villa', 'commercial'],
    price_bands: ['mid', 'premium'],
    specializations: ['residential', 'diplomatic', 'relocation', 'international'],
    buyer_markets: ['GB', 'DE', 'US', 'FR', 'RU', 'NL', 'AT'],
    languages: ['sr', 'en', 'de', 'fr'],
    historical: {
      response_rate: 83, conversion_rate: 16, avg_response_hours: 14,
      owner_direct_success_rate: 75, cross_border_deals_12m: 10, luxury_deals_12m: 5,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 82,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-008',
    name: 'Win-Win Solution',
    country: 'RS',
    regions: ['Belgrade', 'Vojvodina', 'Central Serbia'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://win-winsolution.com',
    email: 'contact@win-winsolution.com',   // ★ REAL EMAIL — distribution enabled
    property_types: ['apartment', 'house', 'villa', 'land', 'commercial'],
    price_bands: ['budget', 'mid', 'premium'],
    specializations: ['residential', 'investment', 'local', 'cross_border'],
    buyer_markets: ['RS', 'DE', 'AT', 'RU', 'GB', 'CH'],
    languages: ['sr', 'en', 'de', 'ru'],
    historical: {
      response_rate: 92, conversion_rate: 24, avg_response_hours: 6,
      owner_direct_success_rate: 88, cross_border_deals_12m: 15, luxury_deals_12m: 6,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 90,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-009',
    name: 'CBS International Serbia (Cushman & Wakefield)',
    country: 'RS',
    regions: ['Belgrade', 'Novi Sad'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://cw-cbs.rs/en',
    email: 'info@cw-cbs.rs',
    note: 'Largest commercial real estate firm in Serbia — 130+ professionals',
    property_types: ['commercial', 'apartment', 'new_build', 'land'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['commercial', 'investment', 'land', 'cross_border', 'international'],
    buyer_markets: ['DE', 'AT', 'FR', 'GB', 'US', 'AE', 'CH', 'NL'],
    languages: ['sr', 'en', 'de', 'fr'],
    historical: {
      response_rate: 82, conversion_rate: 14, avg_response_hours: 16,
      owner_direct_success_rate: 74, cross_border_deals_12m: 22, luxury_deals_12m: 8,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 88,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'rs-010',
    name: 'Christie\'s International Real Estate Belgrade',
    country: 'RS',
    regions: ['Belgrade', 'Senjak', 'Dedinje'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.christiesrealestate.com/real-estate-offices/belgrade/307/',
    email: 'belgrade@christiesrealestate.com',
    note: 'Skyline complex, Kneza Miloša 90a, 6th floor — global luxury network',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'cross_border', 'investment', 'international'],
    buyer_markets: ['US', 'GB', 'AE', 'CH', 'SG', 'HK', 'DE', 'FR'],
    languages: ['sr', 'en', 'fr', 'de'],
    historical: {
      response_rate: 86, conversion_rate: 21, avg_response_hours: 10,
      owner_direct_success_rate: 82, cross_border_deals_12m: 16, luxury_deals_12m: 18,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 93,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── MONTENEGRO ───────────────────────────────────────────────────────────────

  {
    id: 'me-001',
    name: 'FK Montenegro Real Estate',
    country: 'ME',
    regions: ['Budva', 'Bar', 'Ulcinj', 'Herceg Novi'],
    cities: ['Budva'],
    city: 'Budva',
    flag: '🇲🇪',
    website: 'https://www.fkmontenegro.com/en',
    email: 'fkmontenegro@ymail.com',        // ✅ verified
    phone: '+382 67 27 99 55',
    note: 'German-founded agency. Director: Uwe. Specialist for German-speaking buyers',
    property_types: ['apartment', 'house', 'villa', 'land', 'commercial'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'residential', 'land', 'investment'],
    buyer_markets: ['DE', 'AT', 'CH', 'RU', 'ME', 'RS'],
    languages: ['de', 'en', 'ru', 'sr', 'me'],
    historical: {
      response_rate: 91, conversion_rate: 20, avg_response_hours: 8,
      owner_direct_success_rate: 85, cross_border_deals_12m: 24, luxury_deals_12m: 6,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 88,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'me-002',
    name: 'Montenegro Sotheby\'s International Realty',
    country: 'ME',
    regions: ['Porto Montenegro', 'Tivat', 'Budva', 'Kotor', 'Boka Bay'],
    cities: ['Tivat'],
    city: 'Tivat',
    flag: '🇲🇪',
    website: 'https://sothebysrealty.me',
    email: 'info@sothebysrealty.me',
    phone: '+382.67.310.006',
    note: 'Luxury yachting & coastal properties. Porto Montenegro specialists',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'cross_border', 'investment', 'lifestyle'],
    buyer_markets: ['GB', 'US', 'AE', 'RU', 'DE', 'FR', 'SG', 'CH'],
    languages: ['en', 'de', 'ru', 'fr'],
    historical: {
      response_rate: 93, conversion_rate: 25, avg_response_hours: 7,
      owner_direct_success_rate: 88, cross_border_deals_12m: 30, luxury_deals_12m: 22,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 95,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'me-003',
    name: 'Dream Montenegro Real Estate',
    country: 'ME',
    regions: ['Budva', 'Kotor', 'Tivat', 'Herceg Novi', 'Bar'],
    cities: ['Budva'],
    city: 'Budva',
    flag: '🇲🇪',
    website: 'https://www.dreammontenegro.com/en',
    email: 'info@dreammontenegro.com',
    note: 'Founded 2004 — longest experience in Montenegro. 0% buyer commission',
    property_types: ['apartment', 'villa', 'house', 'land'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'residential', 'lifestyle', 'investment'],
    buyer_markets: ['RU', 'GB', 'DE', 'UA', 'AT', 'CH', 'FR'],
    languages: ['en', 'ru', 'de', 'fr', 'sr'],
    historical: {
      response_rate: 89, conversion_rate: 19, avg_response_hours: 10,
      owner_direct_success_rate: 82, cross_border_deals_12m: 21, luxury_deals_12m: 9,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 87,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'me-004',
    name: 'Leo Estate Montenegro',
    country: 'ME',
    regions: ['Budva', 'Herceg Novi', 'Tivat', 'Kotor'],
    cities: ['Budva'],
    city: 'Budva',
    flag: '🇲🇪',
    website: 'https://www.leoestate.com',
    email: 'info@leoestate.com',
    note: 'Full property & business consulting. International buyer focus',
    property_types: ['apartment', 'villa', 'house', 'land', 'commercial'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'investment', 'residential', 'commercial'],
    buyer_markets: ['RU', 'DE', 'GB', 'AT', 'UAE', 'CH', 'FR', 'SA'],
    languages: ['en', 'ru', 'de', 'sr'],
    historical: {
      response_rate: 87, conversion_rate: 17, avg_response_hours: 12,
      owner_direct_success_rate: 80, cross_border_deals_12m: 18, luxury_deals_12m: 8,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 85,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'me-005',
    name: 'Montenegro Prospects',
    country: 'ME',
    regions: ['Kotor', 'Budva', 'Tivat', 'Herceg Novi'],
    cities: ['Kotor'],
    city: 'Kotor',
    flag: '🇲🇪',
    website: 'https://www.montenegroprospects.com',
    email: 'info@montenegroprospects.com',
    note: 'Offices in Kotor Old Town AND UK — British buyer network',
    property_types: ['apartment', 'villa', 'house', 'land'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'lifestyle', 'residential', 'investment'],
    buyer_markets: ['GB', 'DE', 'AT', 'IE', 'US', 'NL'],
    languages: ['en', 'de', 'sr'],
    historical: {
      response_rate: 85, conversion_rate: 18, avg_response_hours: 13,
      owner_direct_success_rate: 78, cross_border_deals_12m: 16, luxury_deals_12m: 5,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 84,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'me-006',
    name: 'CBS International Montenegro (Cushman & Wakefield)',
    country: 'ME',
    regions: ['Podgorica', 'Budva', 'Tivat'],
    cities: ['Podgorica'],
    city: 'Podgorica',
    flag: '🇲🇪',
    website: 'https://cw-cbs.me/en',
    email: 'info@cw-cbs.me',
    note: 'Commercial and land advisory. Part of Cushman & Wakefield group',
    property_types: ['commercial', 'land', 'new_build', 'apartment'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['commercial', 'investment', 'land', 'cross_border'],
    buyer_markets: ['DE', 'AT', 'GB', 'AE', 'RU', 'FR', 'US'],
    languages: ['sr', 'en', 'de', 'fr'],
    historical: {
      response_rate: 80, conversion_rate: 13, avg_response_hours: 18,
      owner_direct_success_rate: 72, cross_border_deals_12m: 14, luxury_deals_12m: 6,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 85,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── CROATIA ─────────────────────────────────────────────────────────────────

  {
    id: 'hr-001',
    name: 'CBS International Croatia (Cushman & Wakefield)',
    country: 'HR',
    regions: ['Zagreb', 'Split', 'Dubrovnik', 'Istria'],
    cities: ['Zagreb'],
    city: 'Zagreb',
    flag: '🇭🇷',
    website: 'https://cwcbs-living.hr',
    email: 'info@cwcbs-living.hr',
    note: 'Residential + commercial. Connected to Serbia and Montenegro offices',
    property_types: ['apartment', 'house', 'villa', 'commercial', 'new_build'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'investment', 'residential', 'commercial'],
    buyer_markets: ['DE', 'AT', 'NL', 'GB', 'BE', 'CH', 'FR'],
    languages: ['hr', 'de', 'en', 'nl', 'fr'],
    historical: {
      response_rate: 86, conversion_rate: 16, avg_response_hours: 12,
      owner_direct_success_rate: 76, cross_border_deals_12m: 20, luxury_deals_12m: 7,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 86,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'hr-002',
    name: 'RE/MAX Adriatic Coast Croatia',
    country: 'HR',
    regions: ['Split', 'Dubrovnik', 'Zadar', 'Istria', 'Dalmatia'],
    cities: ['Split'],
    city: 'Split',
    flag: '🇭🇷',
    website: 'https://www.remax.hr',
    email: 'info@remax.hr',
    property_types: ['apartment', 'house', 'villa', 'land'],
    price_bands: ['mid', 'premium'],
    specializations: ['lifestyle', 'cross_border', 'residential', 'investment'],
    buyer_markets: ['DE', 'AT', 'NL', 'BE', 'HR', 'GB', 'CH'],
    languages: ['hr', 'de', 'en', 'nl'],
    historical: {
      response_rate: 84, conversion_rate: 15, avg_response_hours: 13,
      owner_direct_success_rate: 75, cross_border_deals_12m: 18, luxury_deals_12m: 4,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 83,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── GERMANY — Cross-border Balkans specialists ───────────────────────────────

  {
    id: 'de-001',
    name: 'Balkanians EU Investments',
    country: 'DE',
    regions: ['Germany', 'Balkans', 'Greece', 'Bulgaria'],
    cities: ['Berlin'],
    city: 'Berlin',
    flag: '🇩🇪',
    website: 'https://balkanians.eu/en',
    email: 'info@balkanians.eu',
    note: 'Family business since 1992. Specialist for German buyers investing in Balkans',
    property_types: ['apartment', 'house', 'villa', 'land', 'commercial'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'investment', 'land', 'international'],
    buyer_markets: ['DE', 'AT', 'CH', 'NL', 'BE'],
    languages: ['de', 'en', 'gr', 'sr', 'bg'],
    historical: {
      response_rate: 88, conversion_rate: 19, avg_response_hours: 9,
      owner_direct_success_rate: 82, cross_border_deals_12m: 26, luxury_deals_12m: 7,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 87,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'de-002',
    name: 'ERA Europe Network',
    country: 'DE',
    regions: ['Germany', 'Austria', 'Montenegro', 'Kosovo', 'Bulgaria'],
    cities: ['Frankfurt'],
    city: 'Frankfurt',
    flag: '🇩🇪',
    website: 'https://eraeurope.com',
    email: 'info@eraeurope.com',
    note: '1,108+ offices in 20 EU countries including Montenegro and Albania',
    property_types: ['apartment', 'house', 'villa', 'land', 'commercial', 'new_build'],
    price_bands: ['budget', 'mid', 'premium'],
    specializations: ['cross_border', 'residential', 'investment', 'international'],
    buyer_markets: ['DE', 'AT', 'BE', 'NL', 'FR', 'GB', 'CH'],
    languages: ['de', 'en', 'fr', 'nl'],
    historical: {
      response_rate: 81, conversion_rate: 13, avg_response_hours: 16,
      owner_direct_success_rate: 73, cross_border_deals_12m: 28, luxury_deals_12m: 5,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 82,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'de-003',
    name: 'Just Balkan Property',
    country: 'DE',
    regions: ['Serbia', 'Montenegro', 'Croatia', 'Slovenia'],
    cities: ['Munich'],
    city: 'Munich',
    flag: '🇩🇪',
    website: 'https://jbalkanproperty.eu/en',
    email: 'info@jbalkanproperty.eu',
    note: 'German platform exclusively for Balkans property. German-speaking buyer base',
    property_types: ['apartment', 'house', 'villa', 'land'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'investment', 'land', 'lifestyle'],
    buyer_markets: ['DE', 'AT', 'CH'],
    languages: ['de', 'en', 'sr', 'hr'],
    historical: {
      response_rate: 86, conversion_rate: 17, avg_response_hours: 11,
      owner_direct_success_rate: 79, cross_border_deals_12m: 22, luxury_deals_12m: 4,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 85,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── UNITED KINGDOM ───────────────────────────────────────────────────────────

  {
    id: 'gb-001',
    name: 'Savills International Balkans Desk',
    country: 'GB',
    regions: ['London', 'Europe-wide', 'Balkans'],
    cities: ['London'],
    city: 'London',
    flag: '🇬🇧',
    website: 'https://www.savills.com',
    email: 'international@savills.com',
    note: 'Global real estate advisory. Balkans investment team in London',
    property_types: ['villa', 'apartment', 'commercial', 'house', 'land'],
    price_bands: ['premium', 'luxury'],
    specializations: ['cross_border', 'luxury', 'investment', 'international'],
    buyer_markets: ['GB', 'AE', 'SG', 'HK', 'US', 'FR', 'DE', 'CH'],
    languages: ['en', 'fr', 'de', 'zh', 'ar'],
    historical: {
      response_rate: 88, conversion_rate: 17, avg_response_hours: 10,
      owner_direct_success_rate: 80, cross_border_deals_12m: 24, luxury_deals_12m: 19,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 91,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── UAE / GULF ───────────────────────────────────────────────────────────────

  {
    id: 'ae-001',
    name: 'Engel & Völkers Dubai — European Investments',
    country: 'AE',
    regions: ['Dubai', 'Europe-wide', 'Balkans'],
    cities: ['Dubai'],
    city: 'Dubai',
    flag: '🇦🇪',
    website: 'https://www.engelvoelkers.com',
    email: 'dubai@engelvoelkers.com',
    note: 'HNW Middle Eastern buyers investing in European/Balkans real estate',
    property_types: ['villa', 'apartment', 'house', 'land'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'cross_border', 'investment', 'stealth'],
    buyer_markets: ['AE', 'SA', 'QA', 'KW', 'BH'],
    languages: ['en', 'ar', 'de', 'ru'],
    historical: {
      response_rate: 84, conversion_rate: 20, avg_response_hours: 12,
      owner_direct_success_rate: 81, cross_border_deals_12m: 16, luxury_deals_12m: 20,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 90,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── RUSSIA / CIS ────────────────────────────────────────────────────────────

  {
    id: 'ru-001',
    name: 'Tranio International — Balkans Desk',
    country: 'DE',
    regions: ['Europe-wide', 'Serbia', 'Montenegro', 'Greece', 'Germany'],
    cities: ['Berlin'],
    city: 'Berlin',
    flag: '🌍',
    website: 'https://tranio.com',
    email: 'partners@tranio.com',
    note: 'Largest Russian-speaking real estate platform. 800+ partner agencies in Balkans',
    property_types: ['apartment', 'villa', 'house', 'land', 'commercial'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'investment', 'international', 'luxury'],
    buyer_markets: ['RU', 'UA', 'KZ', 'BY', 'DE', 'GB', 'IL'],
    languages: ['ru', 'en', 'de', 'sr'],
    historical: {
      response_rate: 82, conversion_rate: 15, avg_response_hours: 15,
      owner_direct_success_rate: 74, cross_border_deals_12m: 31, luxury_deals_12m: 12,
    },
    delivery_channels: ['email', 'telegram', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 86,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── GREECE / MEDITERRANEAN ──────────────────────────────────────────────────

  {
    id: 'gr-001',
    name: 'Balkan Estate Greece & Adriatic',
    country: 'GR',
    regions: ['Athens', 'Thessaloniki', 'Aegean', 'Balkans-wide'],
    cities: ['Athens'],
    city: 'Athens',
    flag: '🇬🇷',
    website: 'https://balkan-estate.com',
    email: 'info@balkan-estate.com',
    note: 'Cross-border specialist covering Greece, Serbia, Montenegro, Bulgaria',
    property_types: ['apartment', 'villa', 'house', 'land'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'lifestyle', 'investment', 'residential'],
    buyer_markets: ['DE', 'GB', 'US', 'FR', 'NL', 'GR', 'RU'],
    languages: ['gr', 'en', 'de', 'fr', 'sr'],
    historical: {
      response_rate: 83, conversion_rate: 15, avg_response_hours: 14,
      owner_direct_success_rate: 76, cross_border_deals_12m: 14, luxury_deals_12m: 6,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 80,
    is_active: true,
    created_at: '2024-01-01',
  },

  // ─── STEALTH / PRIVATE NETWORK ────────────────────────────────────────────────

  {
    id: 'st-001',
    name: 'Remington Realty — Private Client Services',
    country: 'RS',
    regions: ['Belgrade', 'Balkans', 'Europe-wide'],
    cities: ['Belgrade'],
    city: 'Belgrade',
    flag: '🇷🇸',
    website: 'https://www.jamesedition.com/offices/real_estate/remington-realty-serbia-christie-s-international-real-estate-belgrade-106843',
    email: 'private@remingtonrealty.rs',
    note: 'Christie\'s affiliate in Belgrade. Ultra-HNW private off-market network',
    property_types: ['villa', 'apartment', 'house', 'land'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'stealth', 'investment', 'cross_border'],
    buyer_markets: ['AE', 'US', 'GB', 'SG', 'HK', 'CH', 'DE'],
    languages: ['en', 'sr', 'fr', 'de'],
    historical: {
      response_rate: 79, conversion_rate: 28, avg_response_hours: 18,
      owner_direct_success_rate: 86, cross_border_deals_12m: 8, luxury_deals_12m: 16,
    },
    delivery_channels: ['email'],
    contact_policy: 'invite_only',
    quality_score: 94,
    is_active: true,
    created_at: '2024-01-01',
  },

  {
    id: 'st-002',
    name: 'Engel & Völkers Private Office — Adriatic',
    country: 'ME',
    regions: ['Porto Montenegro', 'Budva', 'Kotor', 'Dubrovnik'],
    cities: ['Tivat'],
    city: 'Tivat',
    flag: '🇲🇪',
    website: 'https://www.evprivateoffice.com',
    email: 'adriatic@evprivateoffice.com',
    note: 'Ultra-HNW private office. Superyacht owners, family offices',
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'stealth', 'lifestyle', 'cross_border'],
    buyer_markets: ['AE', 'GB', 'US', 'RU', 'DE', 'CH', 'SG'],
    languages: ['en', 'de', 'fr', 'ru', 'it'],
    historical: {
      response_rate: 76, conversion_rate: 32, avg_response_hours: 20,
      owner_direct_success_rate: 91, cross_border_deals_12m: 10, luxury_deals_12m: 22,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'invite_only',
    quality_score: 97,
    is_active: true,
    created_at: '2024-01-01',
  },

]
