/**
 * Demo agency pool — used for testing without a live database
 * In production these come from the PostgreSQL agencies table
 */

import type { Agency } from './engine'

export const DEMO_AGENCY_POOL: Agency[] = [
  {
    id: 'ag-001',
    name: 'Engel & Völkers Adriatic',
    country: 'ME',
    regions: ['Coast'],
    property_types: ['villa', 'apartment', 'house'],
    price_bands: ['premium', 'luxury'],
    specializations: ['cross_border', 'luxury', 'investment'],
    buyer_markets: ['DE', 'AT', 'CH', 'RU', 'GB', 'AE'],
    languages: ['de', 'en', 'ru'],
    historical: {
      response_rate: 94,
      conversion_rate: 22,
      avg_response_hours: 6,
      owner_direct_success_rate: 88,
      cross_border_deals_12m: 34,
      luxury_deals_12m: 18,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 96,
    is_active: true,
    created_at: '2024-01-15',
  },
  {
    id: 'ag-002',
    name: 'Savills International',
    country: 'GB',
    property_types: ['villa', 'apartment', 'commercial', 'house'],
    price_bands: ['premium', 'luxury'],
    specializations: ['cross_border', 'luxury', 'investment'],
    buyer_markets: ['GB', 'AE', 'SG', 'HK', 'US', 'FR', 'DE'],
    languages: ['en', 'fr', 'de', 'zh'],
    historical: {
      response_rate: 91,
      conversion_rate: 18,
      avg_response_hours: 8,
      owner_direct_success_rate: 82,
      cross_border_deals_12m: 28,
      luxury_deals_12m: 22,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 93,
    is_active: true,
    created_at: '2024-02-01',
  },
  {
    id: 'ag-003',
    name: 'RE/MAX Adriatic Coast',
    country: 'HR',
    property_types: ['apartment', 'house', 'villa', 'land'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'residential'],
    buyer_markets: ['DE', 'NL', 'BE', 'AT', 'HR', 'GB'],
    languages: ['hr', 'de', 'en', 'nl'],
    historical: {
      response_rate: 88,
      conversion_rate: 16,
      avg_response_hours: 10,
      owner_direct_success_rate: 78,
      cross_border_deals_12m: 19,
      luxury_deals_12m: 3,
    },
    delivery_channels: ['email', 'whatsapp', 'telegram'],
    contact_policy: 'open',
    quality_score: 89,
    is_active: true,
    created_at: '2024-01-20',
  },
  {
    id: 'ag-004',
    name: 'Knight Frank Serbia',
    country: 'RS',
    property_types: ['apartment', 'house', 'commercial', 'new_build'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'investment', 'commercial'],
    buyer_markets: ['RS', 'RU', 'UA', 'KZ', 'DE', 'CN'],
    languages: ['sr', 'ru', 'en', 'de'],
    historical: {
      response_rate: 85,
      conversion_rate: 15,
      avg_response_hours: 12,
      owner_direct_success_rate: 76,
      cross_border_deals_12m: 14,
      luxury_deals_12m: 6,
    },
    delivery_channels: ['email', 'telegram'],
    contact_policy: 'open',
    quality_score: 86,
    is_active: true,
    created_at: '2024-03-01',
  },
  {
    id: 'ag-005',
    name: 'Tranio Partners Network',
    country: 'DE',
    property_types: ['apartment', 'villa', 'commercial', 'new_build', 'house'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'investment', 'international'],
    buyer_markets: ['DE', 'AT', 'CH', 'FR', 'IT', 'ES', 'GB', 'RU'],
    languages: ['de', 'en', 'ru', 'fr'],
    historical: {
      response_rate: 82,
      conversion_rate: 14,
      avg_response_hours: 14,
      owner_direct_success_rate: 73,
      cross_border_deals_12m: 31,
      luxury_deals_12m: 9,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 84,
    is_active: true,
    created_at: '2024-01-10',
  },
  {
    id: 'ag-006',
    name: 'Century 21 Montenegro',
    country: 'ME',
    property_types: ['apartment', 'house', 'land'],
    price_bands: ['budget', 'mid'],
    specializations: ['residential'],
    buyer_markets: ['ME', 'RS', 'BA', 'HR'],
    languages: ['sr', 'en'],
    historical: {
      response_rate: 79,
      conversion_rate: 12,
      avg_response_hours: 18,
      owner_direct_success_rate: 68,
      cross_border_deals_12m: 4,
      luxury_deals_12m: 0,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 75,
    is_active: true,
    created_at: '2024-04-01',
  },
  {
    id: 'ag-007',
    name: 'Sotheby\'s Realty Montenegro',
    country: 'ME',
    property_types: ['villa', 'apartment'],
    price_bands: ['luxury'],
    specializations: ['luxury', 'cross_border', 'investment'],
    buyer_markets: ['US', 'GB', 'AE', 'SG', 'HK', 'CH'],
    languages: ['en', 'de', 'fr'],
    historical: {
      response_rate: 97,
      conversion_rate: 31,
      avg_response_hours: 4,
      owner_direct_success_rate: 92,
      cross_border_deals_12m: 12,
      luxury_deals_12m: 11,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 98,
    is_active: true,
    created_at: '2024-01-05',
  },
  {
    id: 'ag-008',
    name: 'Realtor.com International Partners',
    country: 'US',
    property_types: ['apartment', 'villa', 'house', 'commercial'],
    price_bands: ['mid', 'premium', 'luxury'],
    specializations: ['cross_border', 'international', 'investment'],
    buyer_markets: ['US', 'CA', 'MX', 'BR', 'AU'],
    languages: ['en', 'es', 'pt'],
    historical: {
      response_rate: 76,
      conversion_rate: 11,
      avg_response_hours: 20,
      owner_direct_success_rate: 65,
      cross_border_deals_12m: 8,
      luxury_deals_12m: 3,
    },
    delivery_channels: ['email'],
    contact_policy: 'open',
    quality_score: 80,
    is_active: true,
    created_at: '2024-02-15',
  },
  {
    id: 'ag-009',
    name: 'Gulf Property Investments',
    country: 'AE',
    property_types: ['villa', 'apartment', 'commercial'],
    price_bands: ['premium', 'luxury'],
    specializations: ['luxury', 'cross_border', 'investment'],
    buyer_markets: ['AE', 'SA', 'QA', 'KW', 'BH', 'OM'],
    languages: ['ar', 'en', 'ru'],
    historical: {
      response_rate: 88,
      conversion_rate: 19,
      avg_response_hours: 9,
      owner_direct_success_rate: 80,
      cross_border_deals_12m: 22,
      luxury_deals_12m: 17,
    },
    delivery_channels: ['email', 'whatsapp'],
    contact_policy: 'open',
    quality_score: 90,
    is_active: true,
    created_at: '2024-01-25',
  },
  {
    id: 'ag-010',
    name: 'Scandinavian Property Group',
    country: 'SE',
    property_types: ['villa', 'house', 'apartment'],
    price_bands: ['mid', 'premium'],
    specializations: ['cross_border', 'lifestyle'],
    buyer_markets: ['SE', 'NO', 'DK', 'FI', 'NL', 'DE'],
    languages: ['sv', 'no', 'da', 'en', 'de'],
    historical: {
      response_rate: 83,
      conversion_rate: 13,
      avg_response_hours: 15,
      owner_direct_success_rate: 72,
      cross_border_deals_12m: 16,
      luxury_deals_12m: 2,
    },
    delivery_channels: ['email', 'telegram'],
    contact_policy: 'open',
    quality_score: 82,
    is_active: true,
    created_at: '2024-03-10',
  },
  // Blacklisted — should not appear in any results
  {
    id: 'ag-099',
    name: 'Blocked Agency',
    country: 'XX',
    property_types: ['apartment'],
    price_bands: ['mid'],
    specializations: [],
    buyer_markets: ['DE'],
    languages: ['en'],
    historical: {
      response_rate: 10,
      conversion_rate: 1,
      avg_response_hours: 72,
      owner_direct_success_rate: 5,
      cross_border_deals_12m: 0,
      luxury_deals_12m: 0,
    },
    delivery_channels: ['email'],
    contact_policy: 'blacklisted',
    quality_score: 5,
    is_active: false,
    created_at: '2023-01-01',
  },
]
